# Built a Python-based web scraper to extract structured country-level data including population, capital, and area from a public website.

In [2]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [4]:
url = "https://www.scrapethissite.com/pages/simple/"

headers = {"User-Agent": "Mozilla/5.0"}

res = requests.get(url, headers = headers)
if res.status_code == 200:
    with open ("web_scrapping_1_original.html" , 'w' , encoding="utf-8") as f:
        f.write(res.text)
else :
    print("Error in scrapping")

In [5]:
with open ("web_scrapping_1_original.html" , "r" , encoding="utf-8") as file:
    html_content = file.read()

In [6]:
soup = BeautifulSoup(html_content, "lxml")

In [17]:
countries = soup.select("div.country")

In [18]:
countries

[<div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ad"></i>
                             Andorra
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Andorra la Vella</span><br/>
 <strong>Population:</strong> <span class="country-population">84000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">468.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ae"></i>
                             United Arab Emirates
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Abu Dhabi</span><br/>
 <strong>Population:</strong> <span class="country-population">4975593</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">82880.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-af"></i>
                             Afghanistan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kabul</span><br/>
 <strong>Population:</strong> <span class="country-population">29121286</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">647500.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ag"></i>
                             Antigua and Barbuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">St. John's</span><br/>
 <strong>Population:</strong> <span class="country-population">86754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">443.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ai"></i>
                             Anguilla
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">The Valley</span><br/>
 <strong>Population:</strong> <span class="country-population">13254</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">102.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-al"></i>
                             Albania
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Tirana</span><br/>
 <strong>Population:</strong> <span class="country-population">2986952</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">28748.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-am"></i>
                             Armenia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Yerevan</span><br/>
 <strong>Population:</strong> <span class="country-population">2968000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">29800.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ao"></i>
                             Angola
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Luanda</span><br/>
 <strong>Population:</strong> <span class="country-population">13068161</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1246700.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aq"></i>
                             Antarctica
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1.4E7</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ar"></i>
                             Argentina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Buenos Aires</span><br/>
 <strong>Population:</strong> <span class="country-population">41343201</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2766890.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-as"></i>
                             American Samoa
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Pago Pago</span><br/>
 <strong>Population:</strong> <span class="country-population">57881</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">199.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-at"></i>
                             Austria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Vienna</span><br/>
 <strong>Population:</strong> <span class="country-population">8205000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">83858.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-au"></i>
                             Australia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Canberra</span><br/>
 <strong>Population:</strong> <span class="country-population">21515754</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">7686850.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-aw"></i>
                             Aruba
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Oranjestad</span><br/>
 <strong>Population:</strong> <span class="country-population">71566</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">193.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ax"></i>
                             Åland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Mariehamn</span><br/>
 <strong>Population:</strong> <span class="country-population">26711</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-az"></i>
                             Azerbaijan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Baku</span><br/>
 <strong>Population:</strong> <span class="country-population">8303512</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">86600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ba"></i>
                             Bosnia and Herzegovina
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sarajevo</span><br/>
 <strong>Population:</strong> <span class="country-population">4590000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">51129.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bb"></i>
                             Barbados
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bridgetown</span><br/>
 <strong>Population:</strong> <span class="country-population">285653</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">431.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bd"></i>
                             Bangladesh
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Dhaka</span><br/>
 <strong>Population:</strong> <span class="country-population">156118464</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">144000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-be"></i>
                             Belgium
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brussels</span><br/>
 <strong>Population:</strong> <span class="country-population">10403000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">30510.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bf"></i>
                             Burkina Faso
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ouagadougou</span><br/>
 <strong>Population:</strong> <span class="country-population">16241811</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">274200.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bg"></i>
                             Bulgaria
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sofia</span><br/>
 <strong>Population:</strong> <span class="country-population">7148785</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">110910.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bh"></i>
                             Bahrain
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Manama</span><br/>
 <strong>Population:</strong> <span class="country-population">738004</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">665.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bi"></i>
                             Burundi
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bujumbura</span><br/>
 <strong>Population:</strong> <span class="country-population">9863117</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">27830.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bj"></i>
                             Benin
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Porto-Novo</span><br/>
 <strong>Population:</strong> <span class="country-population">9056010</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">112620.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bl"></i>
                             Saint Barthélemy
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gustavia</span><br/>
 <strong>Population:</strong> <span class="country-population">8450</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">21.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bm"></i>
                             Bermuda
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Hamilton</span><br/>
 <strong>Population:</strong> <span class="country-population">65365</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">53.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bn"></i>
                             Brunei
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bandar Seri Begawan</span><br/>
 <strong>Population:</strong> <span class="country-population">395027</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">5770.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bo"></i>
                             Bolivia
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Sucre</span><br/>
 <strong>Population:</strong> <span class="country-population">9947418</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">1098580.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bq"></i>
                             Bonaire
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kralendijk</span><br/>
 <strong>Population:</strong> <span class="country-population">18012</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">328.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-br"></i>
                             Brazil
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brasília</span><br/>
 <strong>Population:</strong> <span class="country-population">201103330</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">8511965.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bs"></i>
                             Bahamas
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Nassau</span><br/>
 <strong>Population:</strong> <span class="country-population">301790</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">13940.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bt"></i>
                             Bhutan
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Thimphu</span><br/>
 <strong>Population:</strong> <span class="country-population">699847</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">47000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bv"></i>
                             Bouvet Island
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">None</span><br/>
 <strong>Population:</strong> <span class="country-population">0</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">49.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bw"></i>
                             Botswana
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Gaborone</span><br/>
 <strong>Population:</strong> <span class="country-population">2029307</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">600370.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-by"></i>
                             Belarus
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Minsk</span><br/>
 <strong>Population:</strong> <span class="country-population">9685000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">207600.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-bz"></i>
                             Belize
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Belmopan</span><br/>
 <strong>Population:</strong> <span class="country-population">314522</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">22966.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ca"></i>
                             Canada
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Ottawa</span><br/>
 <strong>Population:</strong> <span class="country-population">33679000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">9984670.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cc"></i>
                             Cocos [Keeling] Islands
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">West Island</span><br/>
 <strong>Population:</strong> <span class="country-population">628</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">14.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cd"></i>
                             Democratic Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Kinshasa</span><br/>
 <strong>Population:</strong> <span class="country-population">70916439</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">2345410.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cf"></i>
                             Central African Republic
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bangui</span><br/>
 <strong>Population:</strong> <span class="country-population">4844927</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">622984.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-cg"></i>
                             Republic of the Congo
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Brazzaville</span><br/>
 <strong>Population:</strong> <span class="country-population">3039126</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">342000.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">
 <i class="flag-icon flag-icon-ch"></i>
                             Switzerland
                         </h3>
 <div class="country-info">
 <strong>Capital:</strong> <span class="country-capital">Bern</span><br/>
 <strong>Population:</strong> <span class="country-population">7581000</span><br/>
 <strong>Area (km<sup>2</sup>):</strong> <span class="country-area">41290.0</span><br/>
 </div>
 </div>,
 <div class="col-md-4 country">
 <h3 class="country-name">

In [27]:
data = []
for each in countries:
    name_tag = each.select_one("h3.country-name")
    capital_tag = each.select_one("span.country-capital")
    population_tag = each.select_one("span.country-population")
    area_tag = each.select_one("span.country-area")

    name = name_tag.text.strip() if name_tag else None
    capital = capital_tag.text.strip() if capital_tag else None
    population = int(population_tag.text.strip()) if population_tag else None 
    area = float(area_tag.text.strip()) if area_tag else None

    data.append({
        "Name" : name,
        "Capital" : capital,
        "Population" : population,
        "Area" : area
    })

In [28]:
data

[{'Name': 'Andorra',
  'Capital': 'Andorra la Vella',
  'Population': 84000,
  'Area': 468.0},
 {'Name': 'United Arab Emirates',
  'Capital': 'Abu Dhabi',
  'Population': 4975593,
  'Area': 82880.0},
 {'Name': 'Afghanistan',
  'Capital': 'Kabul',
  'Population': 29121286,
  'Area': 647500.0},
 {'Name': 'Antigua and Barbuda',
  'Capital': "St. John's",
  'Population': 86754,
  'Area': 443.0},
 {'Name': 'Anguilla',
  'Capital': 'The Valley',
  'Population': 13254,
  'Area': 102.0},
 {'Name': 'Albania',
  'Capital': 'Tirana',
  'Population': 2986952,
  'Area': 28748.0},
 {'Name': 'Armenia',
  'Capital': 'Yerevan',
  'Population': 2968000,
  'Area': 29800.0},
 {'Name': 'Angola',
  'Capital': 'Luanda',
  'Population': 13068161,
  'Area': 1246700.0},
 {'Name': 'Antarctica',
  'Capital': 'None',
  'Population': 0,
  'Area': 14000000.0},
 {'Name': 'Argentina',
  'Capital': 'Buenos Aires',
  'Population': 41343201,
  'Area': 2766890.0},
 {'Name': 'American Samoa',
  'Capital': 'Pago Pago',
  'Population': 57881,
  'Area': 199.0},
 {'Name': 'Austria',
  'Capital': 'Vienna',
  'Population': 8205000,
  'Area': 83858.0},
 {'Name': 'Australia',
  'Capital': 'Canberra',
  'Population': 21515754,
  'Area': 7686850.0},
 {'Name': 'Aruba',
  'Capital': 'Oranjestad',
  'Population': 71566,
  'Area': 193.0},
 {'Name': 'Åland',
  'Capital': 'Mariehamn',
  'Population': 26711,
  'Area': 1580.0},
 {'Name': 'Azerbaijan',
  'Capital': 'Baku',
  'Population': 8303512,
  'Area': 86600.0},
 {'Name': 'Bosnia and Herzegovina',
  'Capital': 'Sarajevo',
  'Population': 4590000,
  'Area': 51129.0},
 {'Name': 'Barbados',
  'Capital': 'Bridgetown',
  'Population': 285653,
  'Area': 431.0},
 {'Name': 'Bangladesh',
  'Capital': 'Dhaka',
  'Population': 156118464,
  'Area': 144000.0},
 {'Name': 'Belgium',
  'Capital': 'Brussels',
  'Population': 10403000,
  'Area': 30510.0},
 {'Name': 'Burkina Faso',
  'Capital': 'Ouagadougou',
  'Population': 16241811,
  'Area': 274200.0},
 {'Name': 'Bulgaria',
  'Capital': 'Sofia',
  'Population': 7148785,
  'Area': 110910.0},
 {'Name': 'Bahrain', 'Capital': 'Manama', 'Population': 738004, 'Area': 665.0},
 {'Name': 'Burundi',
  'Capital': 'Bujumbura',
  'Population': 9863117,
  'Area': 27830.0},
 {'Name': 'Benin',
  'Capital': 'Porto-Novo',
  'Population': 9056010,
  'Area': 112620.0},
 {'Name': 'Saint Barthélemy',
  'Capital': 'Gustavia',
  'Population': 8450,
  'Area': 21.0},
 {'Name': 'Bermuda', 'Capital': 'Hamilton', 'Population': 65365, 'Area': 53.0},
 {'Name': 'Brunei',
  'Capital': 'Bandar Seri Begawan',
  'Population': 395027,
  'Area': 5770.0},
 {'Name': 'Bolivia',
  'Capital': 'Sucre',
  'Population': 9947418,
  'Area': 1098580.0},
 {'Name': 'Bonaire',
  'Capital': 'Kralendijk',
  'Population': 18012,
  'Area': 328.0},
 {'Name': 'Brazil',
  'Capital': 'Brasília',
  'Population': 201103330,
  'Area': 8511965.0},
 {'Name': 'Bahamas',
  'Capital': 'Nassau',
  'Population': 301790,
  'Area': 13940.0},
 {'Name': 'Bhutan',
  'Capital': 'Thimphu',
  'Population': 699847,
  'Area': 47000.0},
 {'Name': 'Bouvet Island', 'Capital': 'None', 'Population': 0, 'Area': 49.0},
 {'Name': 'Botswana',
  'Capital': 'Gaborone',
  'Population': 2029307,
  'Area': 600370.0},
 {'Name': 'Belarus',
  'Capital': 'Minsk',
  'Population': 9685000,
  'Area': 207600.0},
 {'Name': 'Belize',
  'Capital': 'Belmopan',
  'Population': 314522,
  'Area': 22966.0},
 {'Name': 'Canada',
  'Capital': 'Ottawa',
  'Population': 33679000,
  'Area': 9984670.0},
 {'Name': 'Cocos [Keeling] Islands',
  'Capital': 'West Island',
  'Population': 628,
  'Area': 14.0},
 {'Name': 'Democratic Republic of the Congo',
  'Capital': 'Kinshasa',
  'Population': 70916439,
  'Area': 2345410.0},
 {'Name': 'Central African Republic',
  'Capital': 'Bangui',
  'Population': 4844927,
  'Area': 622984.0},
 {'Name': 'Republic of the Congo',
  'Capital': 'Brazzaville',
  'Population': 3039126,
  'Area': 342000.0},
 {'Name': 'Switzerland',
  'Capital': 'Bern',
  'Population': 7581000,
  'Area': 41290.0},
 {'Name': 'Ivory Coast',
  'Capital': 'Yamoussoukro',
  'Population': 21058798,
  'Area': 322460.0},
 {'Name': 'Cook Islands',
  'Capital': 'Avarua',
  'Population': 21388,
  'Area': 240.0},
 {'Name': 'Chile',
  'Capital': 'Santiago',
  'Population': 16746491,
  'Area': 756950.0},
 {'Name': 'Cameroon',
  'Capital': 'Yaoundé',
  'Population': 19294149,
  'Area': 475440.0},
 {'Name': 'China',
  'Capital': 'Beijing',
  'Population': 1330044000,
  'Area': 9596960.0},
 {'Name': 'Colombia',
  'Capital': 'Bogotá',
  'Population': 47790000,
  'Area': 1138910.0},
 {'Name': 'Costa Rica',
  'Capital': 'San José',
  'Population': 4516220,
  'Area': 51100.0},
 {'Name': 'Cuba',
  'Capital': 'Havana',
  'Population': 11423000,
  'Area': 110860.0},
 {'Name': 'Cape Verde',
  'Capital': 'Praia',
  'Population': 508659,
  'Area': 4033.0},
 {'Name': 'Curacao',
  'Capital': 'Willemstad',
  'Population': 141766,
  'Area': 444.0},
 {'Name': 'Christmas Island',
  'Capital': 'Flying Fish Cove',
  'Population': 1500,
  'Area': 135.0},
 {'Name': 'Cyprus',
  'Capital': 'Nicosia',
  'Population': 1102677,
  'Area': 9250.0},
 {'Name': 'Czech Republic',
  'Capital': 'Prague',
  'Population': 10476000,
  'Area': 78866.0},
 {'Name': 'Germany',
  'Capital': 'Berlin',
  'Population': 81802257,
  'Area': 357021.0},
 {'Name': 'Djibouti',
  'Capital': 'Djibouti',
  'Population': 740528,
  'Area': 23000.0},
 {'Name': 'Denmark',
  'Capital': 'Copenhagen',
  'Population': 5484000,
  'Area': 43094.0},
 {'Name': 'Dominica', 'Capital': 'Roseau', 'Population': 72813, 'Area': 754.0},
 {'Name': 'Dominican Republic',
  'Capital': 'Santo Domingo',
  'Population': 9823821,
  'Area': 48730.0},
 {'Name': 'Algeria',
  'Capital': 'Algiers',
  'Population': 34586184,
  'Area': 2381740.0},
 {'Name': 'Ecuador',
  'Capital': 'Quito',
  'Population': 14790608,
  'Area': 283560.0},
 {'Name': 'Estonia',
  'Capital': 'Tallinn',
  'Population': 1291170,
  'Area': 45226.0},
 {'Name': 'Egypt',
  'Capital': 'Cairo',
  'Population': 80471869,
  'Area': 1001450.0},
 {'Name': 'Western Sahara',
  'Capital': 'Laâyoune / El Aaiún',
  'Population': 273008,
  'Area': 266000.0},
 {'Name': 'Eritrea',
  'Capital': 'Asmara',
  'Population': 5792984,
  'Area': 121320.0},
 {'Name': 'Spain',
  'Capital': 'Madrid',
  'Population': 46505963,
  'Area': 504782.0},
 {'Name': 'Ethiopia',
  'Capital': 'Addis Ababa',
  'Population': 88013491,
  'Area': 1127127.0},
 {'Name': 'Finland',
  'Capital': 'Helsinki',
  'Population': 5244000,
  'Area': 337030.0},
 {'Name': 'Fiji', 'Capital': 'Suva', 'Population': 875983, 'Area': 18270.0},
 {'Name': 'Falkland Islands',
  'Capital': 'Stanley',
  'Population': 2638,
  'Area': 12173.0},
 {'Name': 'Micronesia',
  'Capital': 'Palikir',
  'Population': 107708,
  'Area': 702.0},
 {'Name': 'Faroe Islands',
  'Capital': 'Tórshavn',
  'Population': 48228,
  'Area': 1399.0},
 {'Name': 'France',
  'Capital': 'Paris',
  'Population': 64768389,
  'Area': 547030.0},
 {'Name': 'Gabon',
  'Capital': 'Libreville',
  'Population': 1545255,
  'Area': 267667.0},
 {'Name': 'United Kingdom',
  'Capital': 'London',
  'Population': 62348447,
  'Area': 244820.0},
 {'Name': 'Grenada',
  'Capital': "St. George's",
  'Population': 107818,
  'Area': 344.0},
 {'Name': 'Georgia',
  'Capital': 'Tbilisi',
  'Population': 4630000,
  'Area': 69700.0},
 {'Name': 'French Guiana',
  'Capital': 'Cayenne',
  'Population': 195506,
  'Area': 91000.0},
 {'Name': 'Guernsey',
  'Capital': 'St Peter Port',
  'Population': 65228,
  'Area': 78.0},
 {'Name': 'Ghana',
  'Capital': 'Accra',
  'Population': 24339838,
  'Area': 239460.0},
 {'Name': 'Gibraltar',
  'Capital': 'Gibraltar',
  'Population': 27884,
  'Area': 6.5},
 {'Name': 'Greenland',
  'Capital': 'Nuuk',
  'Population': 56375,
  'Area': 2166086.0},
 {'Name': 'Gambia',
  'Capital': 'Bathurst',
  'Population': 1593256,
  'Area': 11300.0},
 {'Name': 'Guinea',
  'Capital': 'Conakry',
  'Population': 10324025,
  'Area': 245857.0},
 {'Name': 'Guadeloupe',
  'Capital': 'Basse-Terre',
  'Population': 443000,
  'Area': 1780.0},
 {'Name': 'Equatorial Guinea',
  'Capital': 'Malabo',
  'Population': 1014999,
  'Area': 28051.0},
 {'Name': 'Greece',
  'Capital': 'Athens',
  'Population': 11000000,
  'Area': 131940.0},
 {'Name': 'South Georgia and the South Sandwich Islands',
  'Capital': 'Grytviken',
  'Population': 30,
  'Area': 3903.0},
 {'Name': 'Guatemala',
  'Capital': 'Guatemala City',
  'Population': 13550440,
  'Area': 108890.0},
 {'Name': 'Guam', 'Capital': 'Hagåtña', 'Population': 159358, 'Area': 549.0},
 {'Name': 'Guinea-Bissau',
  'Capital': 'Bissau',
  'Population': 1565126,
  'Area': 36120.0},
 {'Name': 'Guyana',
  'Capital': 'Georgetown',
  'Population': 748486,
  'Area': 214970.0},
 {'Name': 'Hong Kong',
  'Capital': 'Hong Kong',
  'Population': 6898686,
  'Area': 1092.0},
 {'Name': 'Heard Island and McDonald Islands',
  'Capital': 'None',
  'Population': 0,
  'Area': 412.0},
 {'Name': 'Honduras',
  'Capital': 'Tegucigalpa',
  'Population': 7989415,
  'Area': 112090.0},
 {'Name': 'Croatia',
  'Capital': 'Zagreb',
  'Population': 4491000,
  'Area': 56542.0},
 {'Name': 'Haiti',
  'Capital': 'Port-au-Prince',
  'Population': 9648924,
  'Area': 27750.0},
 {'Name': 'Hungary',
  'Capital': 'Budapest',
  'Population': 9982000,
  'Area': 93030.0},
 {'Name': 'Indonesia',
  'Capital': 'Jakarta',
  'Population': 242968342,
  'Area': 1919440.0},
 {'Name': 'Ireland',
  'Capital': 'Dublin',
  'Population': 4622917,
  'Area': 70280.0},
 {'Name': 'Israel', 'Capital': 'None', 'Population': 7353985, 'Area': 20770.0},
 {'Name': 'Isle of Man',
  'Capital': 'Douglas',
  'Population': 75049,
  'Area': 572.0},
 {'Name': 'India',
  'Capital': 'New Delhi',
  'Population': 1173108018,
  'Area': 3287590.0},
 {'Name': 'British Indian Ocean Territory',
  'Capital': 'None',
  'Population': 4000,
  'Area': 60.0},
 {'Name': 'Iraq',
  'Capital': 'Baghdad',
  'Population': 29671605,
  'Area': 437072.0},
 {'Name': 'Iran',
  'Capital': 'Tehran',
  'Population': 76923300,
  'Area': 1648000.0},
 {'Name': 'Iceland',
  'Capital': 'Reykjavik',
  'Population': 308910,
  'Area': 103000.0},
 {'Name': 'Italy',
  'Capital': 'Rome',
  'Population': 60340328,
  'Area': 301230.0},
 {'Name': 'Jersey',
  'Capital': 'Saint Helier',
  'Population': 90812,
  'Area': 116.0},
 {'Name': 'Jamaica',
  'Capital': 'Kingston',
  'Population': 2847232,
  'Area': 10991.0},
 {'Name': 'Jordan',
  'Capital': 'Amman',
  'Population': 6407085,
  'Area': 92300.0},
 {'Name': 'Japan',
  'Capital': 'Tokyo',
  'Population': 127288000,
  'Area': 377835.0},
 {'Name': 'Kenya',
  'Capital': 'Nairobi',
  'Population': 40046566,
  'Area': 582650.0},
 {'Name': 'Kyrgyzstan',
  'Capital': 'Bishkek',
  'Population': 5776500,
  'Area': 198500.0},
 {'Name': 'Cambodia',
  'Capital': 'Phnom Penh',
  'Population': 14453680,
  'Area': 181040.0},
 {'Name': 'Kiribati', 'Capital': 'Tarawa', 'Population': 92533, 'Area': 811.0},
 {'Name': 'Comoros',
  'Capital': 'Moroni',
  'Population': 773407,
  'Area': 2170.0},
 {'Name': 'Saint Kitts and Nevis',
  'Capital': 'Basseterre',
  'Population': 51134,
  'Area': 261.0},
 {'Name': 'North Korea',
  'Capital': 'Pyongyang',
  'Population': 22912177,
  'Area': 120540.0},
 {'Name': 'South Korea',
  'Capital': 'Seoul',
  'Population': 48422644,
  'Area': 98480.0},
 {'Name': 'Kuwait',
  'Capital': 'Kuwait City',
  'Population': 2789132,
  'Area': 17820.0},
 {'Name': 'Cayman Islands',
  'Capital': 'George Town',
  'Population': 44270,
  'Area': 262.0},
 {'Name': 'Kazakhstan',
  'Capital': 'Astana',
  'Population': 15340000,
  'Area': 2717300.0},
 {'Name': 'Laos',
  'Capital': 'Vientiane',
  'Population': 6368162,
  'Area': 236800.0},
 {'Name': 'Lebanon',
  'Capital': 'Beirut',
  'Population': 4125247,
  'Area': 10400.0},
 {'Name': 'Saint Lucia',
  'Capital': 'Castries',
  'Population': 160922,
  'Area': 616.0},
 {'Name': 'Liechtenstein',
  'Capital': 'Vaduz',
  'Population': 35000,
  'Area': 160.0},
 {'Name': 'Sri Lanka',
  'Capital': 'Colombo',
  'Population': 21513990,
  'Area': 65610.0},
 {'Name': 'Liberia',
  'Capital': 'Monrovia',
  'Population': 3685076,
  'Area': 111370.0},
 {'Name': 'Lesotho',
  'Capital': 'Maseru',
  'Population': 1919552,
  'Area': 30355.0},
 {'Name': 'Lithuania',
  'Capital': 'Vilnius',
  'Population': 2944459,
  'Area': 65200.0},
 {'Name': 'Luxembourg',
  'Capital': 'Luxembourg',
  'Population': 497538,
  'Area': 2586.0},
 {'Name': 'Latvia', 'Capital': 'Riga', 'Population': 2217969, 'Area': 64589.0},
 {'Name': 'Libya',
  'Capital': 'Tripoli',
  'Population': 6461454,
  'Area': 1759540.0},
 {'Name': 'Morocco',
  'Capital': 'Rabat',
  'Population': 31627428,
  'Area': 446550.0},
 {'Name': 'Monaco', 'Capital': 'Monaco', 'Population': 32965, 'Area': 1.95},
 {'Name': 'Moldova',
  'Capital': 'Chişinău',
  'Population': 4324000,
  'Area': 33843.0},
 {'Name': 'Montenegro',
  'Capital': 'Podgorica',
  'Population': 666730,
  'Area': 14026.0},
 {'Name': 'Saint Martin',
  'Capital': 'Marigot',
  'Population': 35925,
  'Area': 53.0},
 {'Name': 'Madagascar',
  'Capital': 'Antananarivo',
  'Population': 21281844,
  'Area': 587040.0},
 {'Name': 'Marshall Islands',
  'Capital': 'Majuro',
  'Population': 65859,
  'Area': 181.3},
 {'Name': 'Macedonia',
  'Capital': 'Skopje',
  'Population': 2062294,
  'Area': 25333.0},
 {'Name': 'Mali',
  'Capital': 'Bamako',
  'Population': 13796354,
  'Area': 1240000.0},
 {'Name': 'Myanmar [Burma]',
  'Capital': 'Naypyitaw',
  'Population': 53414374,
  'Area': 678500.0},
 {'Name': 'Mongolia',
  'Capital': 'Ulan Bator',
  'Population': 3086918,
  'Area': 1565000.0},
 {'Name': 'Macao', 'Capital': 'Macao', 'Population': 449198, 'Area': 254.0},
 {'Name': 'Northern Mariana Islands',
  'Capital': 'Saipan',
  'Population': 53883,
  'Area': 477.0},
 {'Name': 'Martinique',
  'Capital': 'Fort-de-France',
  'Population': 432900,
  'Area': 1100.0},
 {'Name': 'Mauritania',
  'Capital': 'Nouakchott',
  'Population': 3205060,
  'Area': 1030700.0},
 {'Name': 'Montserrat',
  'Capital': 'Plymouth',
  'Population': 9341,
  'Area': 102.0},
 {'Name': 'Malta', 'Capital': 'Valletta', 'Population': 403000, 'Area': 316.0},
 {'Name': 'Mauritius',
  'Capital': 'Port Louis',
  'Population': 1294104,
  'Area': 2040.0},
 {'Name': 'Maldives', 'Capital': 'Malé', 'Population': 395650, 'Area': 300.0},
 {'Name': 'Malawi',
  'Capital': 'Lilongwe',
  'Population': 15447500,
  'Area': 118480.0},
 {'Name': 'Mexico',
  'Capital': 'Mexico City',
  'Population': 112468855,
  'Area': 1972550.0},
 {'Name': 'Malaysia',
  'Capital': 'Kuala Lumpur',
  'Population': 28274729,
  'Area': 329750.0},
 {'Name': 'Mozambique',
  'Capital': 'Maputo',
  'Population': 22061451,
  'Area': 801590.0},
 {'Name': 'Namibia',
  'Capital': 'Windhoek',
  'Population': 2128471,
  'Area': 825418.0},
 {'Name': 'New Caledonia',
  'Capital': 'Noumea',
  'Population': 216494,
  'Area': 19060.0},
 {'Name': 'Niger',
  'Capital': 'Niamey',
  'Population': 15878271,
  'Area': 1267000.0},
 {'Name': 'Norfolk Island',
  'Capital': 'Kingston',
  'Population': 1828,
  'Area': 34.6},
 {'Name': 'Nigeria',
  'Capital': 'Abuja',
  'Population': 154000000,
  'Area': 923768.0},
 {'Name': 'Nicaragua',
  'Capital': 'Managua',
  'Population': 5995928,
  'Area': 129494.0},
 {'Name': 'Netherlands',
  'Capital': 'Amsterdam',
  'Population': 16645000,
  'Area': 41526.0},
 {'Name': 'Norway',
  'Capital': 'Oslo',
  'Population': 5009150,
  'Area': 324220.0},
 {'Name': 'Nepal',
  'Capital': 'Kathmandu',
  'Population': 28951852,
  'Area': 140800.0},
 {'Name': 'Nauru', 'Capital': 'Yaren', 'Population': 10065, 'Area': 21.0},
 {'Name': 'Niue', 'Capital': 'Alofi', 'Population': 2166, 'Area': 260.0},
 {'Name': 'New Zealand',
  'Capital': 'Wellington',
  'Population': 4252277,
  'Area': 268680.0},
 {'Name': 'Oman',
  'Capital': 'Muscat',
  'Population': 2967717,
  'Area': 212460.0},
 {'Name': 'Panama',
  'Capital': 'Panama City',
  'Population': 3410676,
  'Area': 78200.0},
 {'Name': 'Peru',
  'Capital': 'Lima',
  'Population': 29907003,
  'Area': 1285220.0},
 {'Name': 'French Polynesia',
  'Capital': 'Papeete',
  'Population': 270485,
  'Area': 4167.0},
 {'Name': 'Papua New Guinea',
  'Capital': 'Port Moresby',
  'Population': 6064515,
  'Area': 462840.0},
 {'Name': 'Philippines',
  'Capital': 'Manila',
  'Population': 99900177,
  'Area': 300000.0},
 {'Name': 'Pakistan',
  'Capital': 'Islamabad',
  'Population': 184404791,
  'Area': 803940.0},
 {'Name': 'Poland',
  'Capital': 'Warsaw',
  'Population': 38500000,
  'Area': 312685.0},
 {'Name': 'Saint Pierre and Miquelon',
  'Capital': 'Saint-Pierre',
  'Population': 7012,
  'Area': 242.0},
 {'Name': 'Pitcairn Islands',
  'Capital': 'Adamstown',
  'Population': 46,
  'Area': 47.0},
 {'Name': 'Puerto Rico',
  'Capital': 'San Juan',
  'Population': 3916632,
  'Area': 9104.0},
 {'Name': 'Palestine',
  'Capital': 'None',
  'Population': 3800000,
  'Area': 5970.0},
 {'Name': 'Portugal',
  'Capital': 'Lisbon',
  'Population': 10676000,
  'Area': 92391.0},
 {'Name': 'Palau', 'Capital': 'Melekeok', 'Population': 19907, 'Area': 458.0},
 {'Name': 'Paraguay',
  'Capital': 'Asunción',
  'Population': 6375830,
  'Area': 406750.0},
 {'Name': 'Qatar', 'Capital': 'Doha', 'Population': 840926, 'Area': 11437.0},
 {'Name': 'Réunion',
  'Capital': 'Saint-Denis',
  'Population': 776948,
  'Area': 2517.0},
 {'Name': 'Romania',
  'Capital': 'Bucharest',
  'Population': 21959278,
  'Area': 237500.0},
 {'Name': 'Serbia',
  'Capital': 'Belgrade',
  'Population': 7344847,
  'Area': 88361.0},
 {'Name': 'Russia',
  'Capital': 'Moscow',
  'Population': 140702000,
  'Area': 17100000.0},
 {'Name': 'Rwanda',
  'Capital': 'Kigali',
  'Population': 11055976,
  'Area': 26338.0},
 {'Name': 'Saudi Arabia',
  'Capital': 'Riyadh',
  'Population': 25731776,
  'Area': 1960582.0},
 {'Name': 'Solomon Islands',
  'Capital': 'Honiara',
  'Population': 559198,
  'Area': 28450.0},
 {'Name': 'Seychelles',
  'Capital': 'Victoria',
  'Population': 88340,
  'Area': 455.0},
 {'Name': 'Sudan',
  'Capital': 'Khartoum',
  'Population': 35000000,
  'Area': 1861484.0},
 {'Name': 'Sweden',
  'Capital': 'Stockholm',
  'Population': 9828655,
  'Area': 449964.0},
 {'Name': 'Singapore',
  'Capital': 'Singapore',
  'Population': 4701069,
  'Area': 692.7},
 {'Name': 'Saint Helena',
  'Capital': 'Jamestown',
  'Population': 7460,
  'Area': 410.0},
 {'Name': 'Slovenia',
  'Capital': 'Ljubljana',
  'Population': 2007000,
  'Area': 20273.0},
 {'Name': 'Svalbard and Jan Mayen',
  'Capital': 'Longyearbyen',
  'Population': 2550,
  'Area': 62049.0},
 {'Name': 'Slovakia',
  'Capital': 'Bratislava',
  'Population': 5455000,
  'Area': 48845.0},
 {'Name': 'Sierra Leone',
  'Capital': 'Freetown',
  'Population': 5245695,
  'Area': 71740.0},
 {'Name': 'San Marino',
  'Capital': 'San Marino',
  'Population': 31477,
  'Area': 61.2},
 {'Name': 'Senegal',
  'Capital': 'Dakar',
  'Population': 12323252,
  'Area': 196190.0},
 {'Name': 'Somalia',
  'Capital': 'Mogadishu',
  'Population': 10112453,
  'Area': 637657.0},
 {'Name': 'Suriname',
  'Capital': 'Paramaribo',
  'Population': 492829,
  'Area': 163270.0},
 {'Name': 'South Sudan',
  'Capital': 'Juba',
  'Population': 8260490,
  'Area': 644329.0},
 {'Name': 'São Tomé and Príncipe',
  'Capital': 'São Tomé',
  'Population': 175808,
  'Area': 1001.0},
 {'Name': 'El Salvador',
  'Capital': 'San Salvador',
  'Population': 6052064,
  'Area': 21040.0},
 {'Name': 'Sint Maarten',
  'Capital': 'Philipsburg',
  'Population': 37429,
  'Area': 21.0},
 {'Name': 'Syria',
  'Capital': 'Damascus',
  'Population': 22198110,
  'Area': 185180.0},
 {'Name': 'Swaziland',
  'Capital': 'Mbabane',
  'Population': 1354051,
  'Area': 17363.0},
 {'Name': 'Turks and Caicos Islands',
  'Capital': 'Cockburn Town',
  'Population': 20556,
  'Area': 430.0},
 {'Name': 'Chad',
  'Capital': "N'Djamena",
  'Population': 10543464,
  'Area': 1284000.0},
 {'Name': 'French Southern Territories',
  'Capital': 'Port-aux-Français',

In [29]:
df = pd.DataFrame(data)

In [30]:
df.head()

                   Name           Capital  Population      Area
0               Andorra  Andorra la Vella       84000     468.0
1  United Arab Emirates         Abu Dhabi     4975593   82880.0
2           Afghanistan             Kabul    29121286  647500.0
3   Antigua and Barbuda        St. John's       86754     443.0
4              Anguilla        The Valley       13254     102.0

In [35]:
df.shape

(250, 4)

In [44]:
print("Total countries scraped:", len(df))

Total countries scraped: 250

In [36]:
df.isnull().sum()

Name          0
Capital       0
Population    0
Area          0
dtype: int64

In [38]:
df.duplicated().sum()

np.int64(0)

In [41]:
# Top 10 countries with highest population  

df.sort_values(by="Population" , ascending=False).head(10)

              Name     Capital  Population        Area
47           China     Beijing  1330044000   9596960.0
104          India   New Delhi  1173108018   3287590.0
232  United States  Washington   310232863   9629091.0
100      Indonesia     Jakarta   242968342   1919440.0
30          Brazil    Brasília   201103330   8511965.0
177       Pakistan   Islamabad   184404791    803940.0
18      Bangladesh       Dhaka   156118464    144000.0
163        Nigeria       Abuja   154000000    923768.0
190         Russia      Moscow   140702000  17100000.0
113          Japan       Tokyo   127288000    377835.0

# INSIGHTS 

China is the highest populated country followed by India and then US

In [43]:
# top 10 countries with maximum area

df.sort_values(by = "Area" , ascending= False).head(10)

              Name       Capital  Population        Area
190         Russia        Moscow   140702000  17100000.0
8       Antarctica          None           0  14000000.0
37          Canada        Ottawa    33679000   9984670.0
232  United States    Washington   310232863   9629091.0
47           China       Beijing  1330044000   9596960.0
30          Brazil      Brasília   201103330   8511965.0
12       Australia      Canberra    21515754   7686850.0
104          India     New Delhi  1173108018   3287590.0
9        Argentina  Buenos Aires    41343201   2766890.0
124     Kazakhstan        Astana    15340000   2717300.0

# INSIGHT

Russia has maximum area

In [31]:
df.to_csv("web_scrapping_1.csv" , index= False)